apiVersion: v1
kind: Service
metadata:
  name: service-express-app
spec:
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
